# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Libraries As Research Partner in Digital Humanities
tagline:          'UCLA'
description:      'DH 2019 Pre-conference, Utrecht'
url:
baseurl:          /dh2019-preconference/

author:
  name:           'Dawn Childress'
  url:

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/adholibdh/dh2019-preconference

defaultlang:      eng

t:
  English:
    title:        'Libraries As Research Partner in Digital Humanities'
    description:  'DH 2019 Pre-conference, The Hague'
  Español:
    title:        'Bibliotecas como compañeras en la investigación en humanidades digitales'
    description:  'DH 2019 Pre-conference, The Hague'
